# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:15
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=10, null=True)),
                ('current_order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
